####################################################################
#  GPRIETO LIBRARIES make include file.                            #
#  August 2009                                                     #
####################################################################

#
# This MAKE.INC has information about the libraries that need to 
# be called to compile the entire libraries. 
# Also, where the outputs are to be stored in. 
#

#--------------------------------------------------------------------
# FFTW LIBS
#--------------------------------------------------------------------

FFTW3 =  /usr/lib/libfftw3.a

#
# Location where libraries, binaries and modules are to be put
#

#--------------------------------------------------------------------
# LIB, MOD and BIN folders
#--------------------------------------------------------------------

# Change to whereever you want to put files

LIB =      ./lib/

MOD =      ./mod/

PROG =     ./bin/





